# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
- bundle install

test:
  tags:
    - default
  stage: test
  script:
  - bundle exec jekyll build -d /home/data/gitlab-pages/trace_test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  tags:
    - default
  stage: deploy
  script:
  - bundle exec jekyll build -d /home/data/gitlab-pages/trace
  artifacts:
    paths:
    - public
  only:
  - master
